version: '3.5'

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared:/nginx
    depends_on:
      - web

  # openethereum:
  #   image: ethnode-custom
  #   ports:
  #     - "0.0.0.0:8545:8545"
  #     - "0.0.0.0:8546:8546"
  #     - "0.0.0.0:30303:30303"
  #     - "0.0.0.0:30303:30303/udp"
  #   command: "openethereum -l info  --node-arguments --tracing=on"


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
      # - openethereum
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh

  worker: &worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
      # - openethereum
    command: docker/web/celery/worker/run.sh

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh

